# Generated by Django 4.0.4 on 2022-04-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_goals_user_alter_goals_duration_alter_goals_redeemed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=50)),
                ('offer', models.CharField(max_length=144)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
