# Generated by Django 4.0.4 on 2022-04-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='sponsors',
            field=models.ManyToManyField(to='main_app.sponsor'),
        ),
    ]
